### ISSUE TITLE
Does it works well with pouchdb plugin about" pouchdb-authentication"

### ISSUE THREAD

**Issue by sherylynn** [stockulus/pouchdb-asyncstorage-down#10]
do you have any plan ?

**Comment by stockulus** [comment]
I am not sure about it, seems that the package pouchdb-authentication is designed for browser, so you might get Problems, but just try it.

**Comment by stockulus** [comment]
I tried it, seems to work as expected

**Comment by sherylynn** [comment]
Would you mind to show a sample ？ I still get error

**Comment by sherylynn** [comment]
![70120974454668975](https://cloud.githubusercontent.com/assets/1698595/15278674/822cfed8-1b4e-11e6-9c4a-15a420625258.png)
![237748539711448476](https://cloud.githubusercontent.com/assets/1698595/15278675/826b9ed6-1b4e-11e6-9364-413c86bbc6f8.jpg)

**Comment by stockulus** [comment]
Hi,

There is now a small sample app. can you just create a pull request on it with your Problem, so I can check.

Thanks

**Comment by delkant** [comment]
Hello, So.. does pouchdb-authentication plugin works ok with pouchdb-react-native? I couldn't find any sample app as @stockulus is saying on his comments..

Can anyone confirm this is possible?

**Comment by greenais** [comment]
Yes, I confirm, it does. The usage is straitforward:

```

'use strict';
import PouchDB from 'pouchdb-react-native';
PouchDB.plugin(require('pouchdb-authentication'));

const serverDB = new PouchDB('http://10.0.2.2:5984/test', {skip_setup: true})
const localDB = new PouchDB('test')

const PDB = {};

PDB.replicate = ()=> {
   serverDB.logIn('user-123', '123')
  .then((res)=> {
    console.log(' ==================> logIn res ==================> ', res)
    return localDB.replicate.from(serverDB)
  })
  .then((result)=> {
    console.log(' ==================> complete ==================> ', result)
  })
  .catch((err)=> {
    console.log(' !!!!!!!!!!!!!!!!!! ERR !!!!!!!! ', err)
  })
}

```
